### ISSUE TITLE
Python Version 3.8 - conda-forge fbprophet not working using custom image 

### ISSUE THREAD

**Issue by jaebongchun** [gantry-platform/gantry-aiops#6]
dockhub gtno1chun/note-custom-image:1.0.0을 사용했을 경우 fbprophet 동작하지 않음

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
                                                                               failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - fbprophet -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0']

Your python: python=3.8

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

Note that strict channel priority may have removed packages required for satisfiability.

Note: you may need to restart the kernel to use updated packages.

**Comment by gtno1chun** [comment]
I have updated custom image. 
docker pull gtno1chun/note-custom-image:1.1.0

**Comment by jaebongchun** [comment]
![image](https://user-images.githubusercontent.com/67310735/89011544-7d838280-d34b-11ea-927d-728e54d9626c.png)

정상 동작 확인 완료
![image](https://user-images.githubusercontent.com/67310735/89011649-b0c61180-d34b-11ea-9b8a-4eaeaa187914.png)
