### ISSUE TITLE
install error - existing K8S/Istio cluster

### ISSUE THREAD

**Issue by gtno1chun** [gantry-platform/gantry-aiops#7]
$ kubectl api-resources
error: unable to retrieve the complete list of server APIs: custom.metrics.k8s.io/v1beta1: the server is currently unable to handle the request

**Comment by jaebongchun** [comment]
$ kubectl -n istio-system get pod istio-ingressgateway-85d57dc8bc-8rmmc -o yaml
....
  - name: istio-token
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          audience: istio-ca
          expirationSeconds: 43200
          path: istio-token
....
 Service Account Token Volume Projection 이 쿠버네티스 1.15에서 비활성화 되어있기 때문에 kube-apiserver.yaml 파일에  아래 코드 추가하여 해결 가능합니다. 

$ sudo vi /etc/kubernetes/manifests/kube-apiserver.yaml
...
        - --service-account-signing-key-file=/etc/kubernetes/pki/sa.key
        - --service-account-issuer=api
        - --service-account-api-audiences=api,vault
...

**Comment by gtno1chun** [comment]
> $ kubectl -n istio-system get pod istio-ingressgateway-85d57dc8bc-8rmmc -o yaml
> ....
> 
> * name: istio-token
>   projected:
>   defaultMode: 420
>   sources:
>   
>   * serviceAccountToken:
>     audience: istio-ca
>     expirationSeconds: 43200
>     path: istio-token
>     ....
>     Service Account Token Volume Projection 이 쿠버네티스 1.15에서 비활성화 되어있기 때문에 kube-apiserver.yaml 파일에  아래 코드 추가하여 해결 가능합니다.
> 
> $ sudo vi /etc/kubernetes/manifests/kube-apiserver.yaml
> ...
> - --service-account-signing-key-file=/etc/kubernetes/pki/sa.key
> - --service-account-issuer=api
> - --service-account-api-audiences=api,vault
> ...

It works for me. thanks
