### ISSUE TITLE
ConnectionError: HTTPCoonectionPool 

### ISSUE THREAD

**Issue by jaebongchun** [gantry-platform/gantry-aiops#9]
데이터 수집에서 제공한 URL을 사용했지만 connection error가 발행합니다. 

eorror code: 
ConnectionError: HTTPConnectionPool(host='13.124.167.81', port=32406): Max retries exceeded with url: /api/v1/query_range?query=instance:node_cpu:rate:sum&start=2020-06-01T00:00:00Z&end=2020-08-03T06:26:14Z&step=10m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9135663b50>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by gtno1chun** [comment]
> 데이터 수집에서 제공한 URL을 사용했지만 connection error가 발행합니다.
> 
> eorror code:
> ConnectionError: HTTPConnectionPool(host='13.124.167.81', port=32406): Max retries exceeded with url: /api/v1/query_range?query=instance:node_cpu:rate:sum&start=2020-06-01T00:00:00Z&end=2020-08-03T06:26:14Z&step=10m (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9135663b50>: Failed to establish a new connection: [Errno 111] Connection refused'))

I have got same issue. It was working last week.

**Comment by jaebongchun** [comment]
접속 정보 확인
$ k -n prom get svc 
prometheus-svc 확인 결과 노드포트에 변경이 있음. 

인그레스 연결이 아니기 때문에 포트 변경이 접속 관련 에러 발생. 
향후 버전에 업때 반영 예정.
